Make use of rsync optional in build.sh
ansible-community/antsibull-docs pull request #307
Opened 2024-08-20 16:44 UTC by ssbarnea

Fixes: #306

2024-08-20 18:31 UTC, felixfontein requested changes
The whole reason of using rsync with the temp directory is that Sphinx only rebuilds the changed files in subsequent runs, and that files that should no longer be there are deleted. You cannot simply replace rsync by cp here without breaking both these things.

Instead of doing some silent fallback, I would implement this differently so that the user can pass a flag to `antsibull-docs sphinx-init` that directly lets antsibull-docs write to the destination instead of writing into a temp directory and using rsync. You can then use that option in CI when you start with a clean state anyway and don't need incremental builds.

2024-08-20 18:32 UTC, felixfontein commented
(To re-create the sphinx-init baseline, go to `tests/functional/` and run `./build-sphinx-init-baseline.sh`.)

2024-08-20 22:36 UTC, gotmax23 commented on src/antsibull_docs/data/sphinx_init/build_sh.j2
> +# cspell: disable cprv
We don't use cspell in this repository (whether or not we should is a separate discussion), so it'd be better not to have comments for it cluttering up the sources.

2024-08-23 10:07 UTC, felixfontein commented
I'm planning to do a new feature release of antsibull-docs this weekend. This would be a nice feature to include; when do you plan to continue working on it?

2024-08-24 16:17 UTC, felixfontein commented
#315 implements this differently.

2024-08-24 19:58 UTC, closed without merging